// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1-EDFccGLBnd5tOJuuKTxaKtnE0GMJTs',
    appId: '1:718306433140:web:db7435d2274b0c68d25921',
    messagingSenderId: '718306433140',
    projectId: 'todolist-9fefb',
    authDomain: 'todolist-9fefb.firebaseapp.com',
    storageBucket: 'todolist-9fefb.firebasestorage.app',
    measurementId: 'G-9HSRNNZPZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIvq0BWHGusIm_85RCu6sa1Qg4dQpw3Eo',
    appId: '1:718306433140:android:96ed4c2dc8ab7826d25921',
    messagingSenderId: '718306433140',
    projectId: 'todolist-9fefb',
    storageBucket: 'todolist-9fefb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEb4tAzs5ALsFSWGsnaVsbuESqXt101do',
    appId: '1:718306433140:ios:300a056dc5bbbcfcd25921',
    messagingSenderId: '718306433140',
    projectId: 'todolist-9fefb',
    storageBucket: 'todolist-9fefb.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEb4tAzs5ALsFSWGsnaVsbuESqXt101do',
    appId: '1:718306433140:ios:300a056dc5bbbcfcd25921',
    messagingSenderId: '718306433140',
    projectId: 'todolist-9fefb',
    storageBucket: 'todolist-9fefb.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1-EDFccGLBnd5tOJuuKTxaKtnE0GMJTs',
    appId: '1:718306433140:web:06c341472dd1784fd25921',
    messagingSenderId: '718306433140',
    projectId: 'todolist-9fefb',
    authDomain: 'todolist-9fefb.firebaseapp.com',
    storageBucket: 'todolist-9fefb.firebasestorage.app',
    measurementId: 'G-1M6JJJH533',
  );
}
